# https://github.com/realm/SwiftLint#configuration

disabled_rules:
    - cyclomatic_complexity
    - file_length
    - function_body_length
    - function_parameter_count
    - identifier_name
    - line_length
    - notification_center_detachment
    - syntactic_sugar
    - type_body_length
    - force_unwrapping

opt_in_rules:
    - force_unwrapping

excluded:
    - Pods
    # Code from web
    - ExponeaSDK/ExponeaSDK/Classes/Others/Reachability.swift
    # Code from web
    - ExponeaSDK/ExponeaSDK/Classes/Others/NSManagedObjectContext+Perform.swift
